### ISSUE TITLE
Single payouts on the Rewards App

### ISSUE THREAD

**Issue by joeycharlesworth** [AutarkLabs/feature-requests#31]
When creating a reward on the Rewards App, it would be useful to be able to distribute a one-off dividend payment to token holders based on the number of tokens held by each token holder. This is in contrast to the current functionality that only permits recurring dividends. 

It strikes me as odd functionality to have recurring dividends. If mirroring the working practices of companies, they might intend to pay dividends each quarter for example but legally, can only do so if there is sufficient retained earnings on their balance sheet. The common practice is to have a board meeting (or sometimes shareholder meetings) and then the board (or shareholders) would decide whether or not to issue dividends in a specific period.

**Comment by stellarmagnet** [comment]
This is possible now! Thanks for this request @joeycharlesworth, for what should have been an obvious feature.
