### ISSUE TITLE
Allow organizations to disable/skip the "Request to work + approval" step.

### ISSUE THREAD

**Issue by lkngtn** [AutarkLabs/feature-requests#8]
**Describe a feature you'd like to see and your specific use case**
In some cases an organization may feel like the request to work step is unnecessary, or is better managed via off-chain coordination. It would be great to be able to disable this part of the flow, so tasks states would be `unfunded`, `funded`, `submitted`, `approved`. 

**Describe alternatives you've considered**
I haven't considered other alternatives

**When do you plan to go live as a DAO (or are you currently one?)**
Operating on rinkeby now, will migrate to either xdai or mainnet as soon as it's possible to do so.

**Comment by stellarmagnet** [comment]
This is supported in the contract now, and the frontend is under development. Expect a release next month. Thank you for the request!
